#pragma once

/**
 * glint_window_base.hpp
 * Platform-independent base class for standalone glint tool windows.
 *
 * Contains all state and behaviour that is identical on every OS:
 *   - glint_document ownership
 *   - Skia CPU-raster surface (SkBitmap + SkCanvas)
 *   - Thread/running flag
 *   - Dimension and mouse-delta tracking
 *   - Pure virtual interface for subclasses (identity + layout)
 *   - Optional lifecycle hooks
 *
 * Platform-specific subclasses (glint_window_win32, sk_ui_window_mac, etc.)
 * provide the OS message loop, blitting, and input routing, then call
 * buildUI() / onCreated() / onThreadStarted() / onThreadEnded() / afterRun()
 * at the appropriate points.
 *
 * Include via the umbrella:
 *   #include "glint_window.hpp"
 * which resolves to the correct platform subclass automatically.
 */

#include "../glint_core.hpp"   // scene graph + document types needed by standalone windows

// Backend selection header — generated by init_skia.mjs --backend <name>.
// Must be included before any GLINT_RENDER_GPU / GLINT_RENDER_BACKEND checks.
#if __has_include("../glint_render_backend.h")
#  include "../glint_render_backend.h"
#endif

#include "include/core/SkBitmap.h"
#include "include/core/SkCanvas.h"
#include "include/core/SkColor.h"
#  if (defined(GLINT_RENDER_GPU) && GLINT_RENDER_GPU) || defined(__APPLE__)
// Ganesh (GPU) headers — pulled in for GPU builds and always on Apple (Metal).
#    include "include/gpu/ganesh/GrDirectContext.h"
#    include "include/gpu/ganesh/SkSurfaceGanesh.h"
#  endif // GLINT_RENDER_GPU || __APPLE__

#include <atomic>
#include <memory>
#include <thread>

class glint_window_base
{
public:
  virtual ~glint_window_base() = default;

protected:
  // ── Shared state ──────────────────────────────────────────────────────────

  /** The glint scene graph for this window's own UI.  Created by the
   *  platform subclass in its WM_CREATE / windowDidLoad equivalent, before
   *  buildUI() is called. */
  std::unique_ptr<glint_document> mOwnRoot;

  /** Current window client area size in LOGICAL (CSS) pixels. */
  int   mW = 800;
  int   mH = 600;

  /** Current window client area size in PHYSICAL (backing-store) pixels.
   *  On non-DPI-aware platforms (or at 100% scale) these equal mW/mH. */
  int   mWpx = 800;
  int   mHpx = 600;

  /** Device pixel ratio: physical / logical. 1.f on platforms that keep the
   *  two identical (or defer scaling to the native layer, as on macOS). */
  float mDpr = 1.f;

  /** Previous mouse position — used to compute drag deltas. */
  float mPrevX = 0.f;
  float mPrevY = 0.f;

  /** Background thread that owns the OS window + message loop. */
  std::thread       mThread;
  std::atomic<bool> mRunning{ false };

  /** Active Skia canvas.
   *  CPU path : points into mCpuCanvas (owned by this class).
   *  GPU path : points into mGpuSurface->getCanvas() (owned by the surface).
   *  Either way the lifetime of the pointed-to object covers every call to
   *  paint() / DrawToCanvas(). */
  SkCanvas* mCanvas = nullptr;

  // ── CPU raster surface — always present ──────────────────────────────────
  // Used directly in non-GPU builds, and as a CPU fallback in GPU builds
  // when a subclass overrides useGpu() → false (e.g. glint_colorpicker_window).
  SkBitmap                  mBitmap;
  std::unique_ptr<SkCanvas> mCpuCanvas;

  /** Allocate (or reallocate) the CPU bitmap and wire mCanvas to it.
   *  Called by recreateSurface() in non-GPU builds, and by the win32
   *  recreateSurface() override when useGpu() returns false. */
  void recreateCpuSurface()
  {
    // CPU bitmap lives in PHYSICAL pixels. Document coordinates are logical,
    // the platform subclass applies a DPR transform at paint time.
    const int bmpW = mWpx > 0 ? mWpx : mW;
    const int bmpH = mHpx > 0 ? mHpx : mH;
    if (bmpW <= 0 || bmpH <= 0) return;
    mBitmap.allocN32Pixels(bmpW, bmpH);
    mBitmap.eraseColor(SK_ColorBLACK);
    mCpuCanvas = std::make_unique<SkCanvas>(mBitmap);
    mCanvas = mCpuCanvas.get();
  }

#if (!defined(GLINT_RENDER_GPU) || !(GLINT_RENDER_GPU)) && !defined(__APPLE__)
  /** Non-GPU builds: recreateSurface() delegates to recreateCpuSurface(). */
  virtual void recreateSurface() { recreateCpuSurface(); }

#else // GLINT_RENDER_GPU || __APPLE__
  // ── GPU (Ganesh/GL or Metal) rendering surface ────────────────────────────
  /** Skia GPU context.  Created by glint_window_win32::initGpu() from a live
   *  WGL context; destroyed in destroyGpu() before the WGL context is torn
   *  down. */
  sk_sp<GrDirectContext> mGrContext;

  /** GPU-backed SkSurface wrapping the window's default framebuffer (FBO 0).
   *  Recreated on every resize by the platform override of recreateSurface(). */
  sk_sp<SkSurface>       mGpuSurface;

  /** recreateSurface() is overridden by glint_window_win32 in GPU mode.
   *  The base provides an empty default so non-win32 ports compile cleanly. */
  virtual void recreateSurface() {}

#endif // !GLINT_RENDER_GPU && !__APPLE__

  /** Background clear colour painted before DrawToCanvas() each frame.
   *  Override in subclasses to match the window's visual background. */
  virtual SkColor clearColor() const
  {
    return SkColorSetARGB(255, 20, 20, 20);
  }

  // ── Pure virtual — subclass identity ─────────────────────────────────────

  /** OS-registered window class name (wide string, e.g. L"glint_inspector"). */
  virtual const wchar_t* windowClassName() const = 0;

  /** Window title bar caption (wide string). */
  virtual const wchar_t* windowTitle() const = 0;

  /** Refresh the native window title from the current virtual title getters. */
  virtual void refreshWindowTitle() {}

  /** Called by the platform subclass inside WM_CREATE / windowDidLoad, after
   *  mOwnRoot has been created and its canvas configured as a flex column.
   *  Subclasses populate mOwnRoot->mCanvas with their child components here. */
  virtual void buildUI() = 0;

  // ── Optional overrides — identity ────────────────────────────────────────

  /** Initial width passed to CreateWindowExW / NSWindow (pixels). */
  virtual int defaultWidth()  const { return 800; }

  /** Initial height passed to CreateWindowExW / NSWindow (pixels). */
  virtual int defaultHeight() const { return 600; }

  // ── Optional lifecycle hooks ──────────────────────────────────────────────

  /** Called immediately after buildUI() + recreateSurface() succeed in
   *  WM_CREATE / windowDidLoad.  Use this for post-build initialisation
   *  (e.g. populating a list, refreshing the tree snapshot). */
  virtual void onCreated() {}

  /** Called on the window thread just before the message/run loop starts
   *  (after the HWND is valid).  Subscribe to glint_bus events here. */
  virtual void onThreadStarted() {}

  /** Called on the window thread immediately after the message/run loop exits
   *  (before the HWND atom and mRunning flag are cleared).
   *  Unsubscribe from glint_bus events and clean up here. */
  virtual void onThreadEnded() {}

  /** Called from WM_DESTROY / windowWillClose before the OS message pump
   *  posts the quit signal.  Use for closing sub-windows (e.g. inspector). */
  virtual void onDestroyed() {}

  /** Called at the very end of run(), after mRunning and mHWNDAtom are
   *  cleared.  The inspector overrides this to `delete this` (self-destruct);
   *  most windows leave it as the default no-op. */
  virtual void afterRun() {}
};
