#pragma once

/**
 * glint_view_base.hpp
 * Platform-independent base for embedded/native glint views.
 *
 * A glint view owns a glint_document and the draw surface used to present it
 * inside a host application's native parent view/window.
 *
 * Platform-specific subclasses provide native child view creation, input
 * routing, invalidation, and GPU/CPU presentation.
 */

#include "../glint_core.hpp"

// Backend selection header — generated by init_skia.mjs --backend <name>.
// Must be included before any GLINT_RENDER_GPU / GLINT_RENDER_BACKEND checks.
#if __has_include("../glint_render_backend.h")
#  include "../glint_render_backend.h"
#endif

#include "include/core/SkBitmap.h"
#include "include/core/SkCanvas.h"
#include "include/core/SkColor.h"
#  if (defined(GLINT_RENDER_GPU) && GLINT_RENDER_GPU) || defined(__APPLE__)
#    include "include/gpu/ganesh/GrDirectContext.h"
#    include "include/gpu/ganesh/SkSurfaceGanesh.h"
#    if defined(__APPLE__)
#      include "include/gpu/ganesh/mtl/GrMtlBackendContext.h"
#      include "include/gpu/ganesh/mtl/GrMtlDirectContext.h"
#      include "include/gpu/ganesh/mtl/SkSurfaceMetal.h"
#    endif
#  endif

#include <functional>
#include <memory>

enum class glint_backend
{
  Auto,
  CPU,
  Metal,
  OpenGL,
  D3D11,
  D3D12,
  Vulkan
};

struct glint_view_options
{
  void*         parent = nullptr;
  int           width = 800;
  int           height = 600;
  bool          visible = true;
  glint_backend gpu = glint_backend::Auto;
  std::function<void(glint_document&)> onDocumentCreated;
  SkColor       clearColor = SkColorSetARGB(255, 20, 20, 20);
};

class glint_view_base
{
public:
  explicit glint_view_base(const glint_view_options& options)
    : mOptions(options)
    , mW(options.width)
    , mH(options.height)
    , mWpx(options.width)
    , mHpx(options.height)
  {
  }

  virtual ~glint_view_base() = default;

  glint_document& document()
  {
    return *mDocument;
  }

  const glint_document& document() const
  {
    return *mDocument;
  }

  bool hasDocument() const
  {
    return static_cast<bool>(mDocument);
  }

  glint_backend activeBackend() const
  {
    return mActiveBackend;
  }

  int width() const
  {
    return mW;
  }

  int height() const
  {
    return mH;
  }

  // Physical (backing-store) pixel size. On Win32 this equals mW*mDpr; on
  // platforms that keep logical==physical (or defer scaling to the layer, as
  // on macOS), this matches mW/mH exactly.
  int widthPx() const
  {
    return mWpx;
  }

  int heightPx() const
  {
    return mHpx;
  }

  float devicePixelRatio() const
  {
    return mDpr;
  }

  virtual void* nativeHandle() const = 0;
  virtual void resize(int width, int height) = 0;
  virtual void requestRedraw() = 0;

protected:
  void createDocument(std::function<void()> requestRedraw)
  {
    const glint_rect bounds(0.f, 0.f, static_cast<float>(mW), static_cast<float>(mH));
    mDocument = std::make_unique<glint_document>(bounds, nullptr, std::move(requestRedraw));
  }

  void updateDocumentBounds()
  {
    if (!mDocument)
      return;

    const glint_rect bounds(0.f, 0.f, static_cast<float>(mW), static_cast<float>(mH));
    mDocument->mCanvas.mRect = bounds;
    mDocument->mCanvas.mPaintRECT = bounds;
    mDocument->mCanvas.mParentW = static_cast<float>(mW);
    mDocument->mCanvas.mParentH = static_cast<float>(mH);
  }

  glint_backend preferredBackend() const
  {
    return mOptions.gpu;
  }

  bool shouldUseGpu() const
  {
    switch (mOptions.gpu)
    {
      case glint_backend::CPU:
        return false;

      case glint_backend::Auto:
      case glint_backend::Metal:
      case glint_backend::OpenGL:
      case glint_backend::D3D11:
      case glint_backend::D3D12:
        return true;

      default:
        return false;
    }
  }

  virtual SkColor clearColor() const
  {
    return mOptions.clearColor;
  }

  void recreateCpuSurface()
  {
    if (mW <= 0 || mH <= 0)
      return;

    mBitmap.allocN32Pixels(mW, mH);
    mBitmap.eraseColor(SK_ColorBLACK);
    mCpuCanvas = std::make_unique<SkCanvas>(mBitmap);
    mCanvas = mCpuCanvas.get();
    mActiveBackend = glint_backend::CPU;
  }

  virtual void recreateSurface()
  {
    recreateCpuSurface();
  }

  SkCanvas*                  mCanvas = nullptr;
  SkBitmap                   mBitmap;
  std::unique_ptr<SkCanvas>  mCpuCanvas;
#  if (defined(GLINT_RENDER_GPU) && GLINT_RENDER_GPU) || defined(__APPLE__)
  sk_sp<GrDirectContext>     mGrContext;
  sk_sp<SkSurface>           mGpuSurface;
#  endif

  glint_view_options           mOptions;
  std::unique_ptr<glint_document> mDocument;
  int                          mW = 800;
  int                          mH = 600;
  int                          mWpx = 800;
  int                          mHpx = 600;
  float                        mDpr = 1.f;
  float                        mPrevX = 0.f;
  float                        mPrevY = 0.f;
  glint_backend                mActiveBackend = glint_backend::CPU;
};