#pragma once

// glint_bundle_group_<!id!>.hpp — auto-generated by glint_bundler.mjs, do not edit.

#include "../../glint_bundle_group_root.hpp"

#ifndef __INTELLISENSE__

namespace <!namespace!> {

class glint_bundle_group_<!id!> : public glint_bundle_group_root {
public:
    unsigned int groupID = <!id!>;

#if defined(GLINT_BUNDLE_SHALLOW)
    size_t offsets[<!offsets_arr_size!>] = {<!offsets!>};
    size_t sizes[<!sizes_arr_size!>]     = {<!sizes!>};

    size_t data_size = <!data_size!>;

    glint_bundle_group_<!id!>() {
        getPointersCB = [this](void** _offsets, void** _sizes, void** _data, size_t* _data_size) {
            *_offsets    = (void*)this->offsets;
            *_sizes      = (void*)this->sizes;
            *_data_size  = this->data_size;
            *_data = (void*)this->data.data();
        };
    }
#elif defined(GLINT_BUNDLE_DEEP)
    glint_bundle_group_<!id!>();
#endif

    ~glint_bundle_group_<!id!>() override { getPointersCB = nullptr; }
};

} // namespace <!namespace!>

#endif // __INTELLISENSE__
