#pragma once

// glint_bundle_entry.hpp — auto-generated by glint_bundler.mjs, do not edit.

#include "glint_bundle_group_root.hpp"
#include <string>

namespace <!namespace!> {

class glint_bundle_entry_info {
public:
    size_t idx      = (size_t)-1;
    size_t offset   = (size_t)-1;
    size_t size     = (size_t)-1;
    int    groupIdx = -1;

    bool        isFolder  = false;
    std::string filename;
    std::string folderEntries;
    std::string fileEntries;

    glint_bundle_group_root* group = nullptr;

    glint_bundle_entry_info(
        size_t                   _offset,
        size_t                   _size,
        int                      _groupIdx,
        size_t                   _idx,
        void*                    _group,
        bool                     _isFolder     = false,
        const std::string&       _filename     = "",
        const std::string&       _folderEntries = "",
        const std::string&       _fileEntries   = ""
    ) : offset(_offset), size(_size), groupIdx(_groupIdx), idx(_idx),
        group(static_cast<glint_bundle_group_root*>(_group)),
        isFolder(_isFolder), filename(_filename),
        folderEntries(_folderEntries), fileEntries(_fileEntries) {}
};

} // namespace <!namespace!>
