#pragma once

// glint_bundle_group_root.hpp — auto-generated by glint_bundler.mjs, do not edit.

#include <cstddef>
#include <functional>
#include <vector>

namespace <!namespace!> {

using glint_bundle_get_pointers_cb = std::function<void(void** offsets, void** sizes, void** data, size_t* data_size)>;
using glint_bundle_flush_cache_cb  = std::function<void()>;

class glint_bundle_group_root {
public:
    glint_bundle_get_pointers_cb getPointersCB;
    glint_bundle_flush_cache_cb  flushCacheCB;

#if defined(GLINT_BUNDLE_SHALLOW)
    std::vector<unsigned char> data;
#endif

    virtual void getPointers(void** offsets, void** sizes, void** data, size_t* data_size) {
        if (getPointersCB) getPointersCB(offsets, sizes, data, data_size);
    }

    virtual ~glint_bundle_group_root() { getPointersCB = nullptr; }
};

} // namespace <!namespace!>
