#pragma once

// glint_bundle_library.hpp — auto-generated by glint_bundler.mjs, do not edit.

#include "glint_bundle_include.hpp"
#include "glint_bundle_groups.hpp"
#include "glint_bundle_entry.hpp"
#include "glint_bundle_entries_files.hpp"
#include "glint_bundle_entries_folders.hpp"

#include "glint/utils/glint_path.hpp"

#include <filesystem>
#include <fstream>

namespace <!namespace!> {

class glint_bundle_library {
public:
    glint_bundle_groups          groups;
    glint_bundle_library_Files   fileEntries;
    glint_bundle_library_Folders folderEntries;

    glint_bundle_library() : fileEntries(groups), folderEntries(groups) {}

    static std::string normalizeRequestPath(const std::string& rawPath) {
        if (rawPath.empty())
            return {};

        std::string normalized = std::filesystem::path(rawPath).lexically_normal().generic_string();
        if (!normalized.empty() && normalized.front() != '/')
            normalized.insert(normalized.begin(), '/');

        return normalized;
    }

#if defined(GLINT_BUNDLE_SHALLOW)
    static std::filesystem::path shallowGroupDataPath(int groupIdx) {
        return glint_self_dir() / "bundle" / (std::to_string(groupIdx) + ".bin");
    }

    static bool loadShallowGroup(glint_bundle_group_root& group, int groupIdx) {
        if (!group.data.empty())
            return true;

        const auto dataPath = shallowGroupDataPath(groupIdx);
        std::ifstream stream(dataPath, std::ios::binary | std::ios::ate);
        if (!stream)
            return false;

        const std::streamsize size = stream.tellg();
        if (size < 0)
            return false;

        group.data.resize(static_cast<size_t>(size));
        stream.seekg(0, std::ios::beg);

        if (size > 0 && !stream.read(reinterpret_cast<char*>(group.data.data()), size)) {
            group.data.clear();
            return false;
        }

        return true;
    }
#endif

    glint_bundle_entry_info* findByPath(const std::string& path) {
        const std::string normalizedPath = normalizeRequestPath(path);
        auto fileIt   = fileEntries.find(normalizedPath);
        auto folderIt = folderEntries.find(normalizedPath);

        if (fileIt == fileEntries.end() && folderIt == folderEntries.end())
            return nullptr;

        if (fileIt != fileEntries.end()) {
            auto* entry = fileIt->second;

#if defined(GLINT_BUNDLE_SHALLOW)
            auto* grp = static_cast<glint_bundle_group_root*>(groups[entry->groupIdx]);
            if (!loadShallowGroup(*grp, entry->groupIdx))
                return nullptr;
#endif
            return entry;
        }

        return folderIt->second;
    }

    // Dispatches a glint_resource_request to fromBuffer() if the path is in the bundle.
    // Returns true if served, false if not found so the caller can decide how to handle misses.
    template <typename TRequest>
    bool dispatch(TRequest& req) {
        auto* entry = findByPath(req.pathname);
        if (!entry || entry->isFolder) return false;

        void* offsets  = nullptr;
        void* sizes    = nullptr;
        void* data     = nullptr;
        size_t sz      = 0;

        auto* grp = static_cast<glint_bundle_group_root*>(groups[entry->groupIdx]);
        grp->getPointers(&offsets, &sizes, &data, &sz);

        if (!data) return false;

        req.fromBuffer(static_cast<const unsigned char*>(data) + entry->offset, entry->size);
        return true;
    }
};

} // namespace <!namespace!>
