#pragma once

// glint_bundle_groups.hpp — auto-generated by glint_bundler.mjs, do not edit.

#include "glint_bundle_group_root.hpp"
#include <vector>

namespace <!namespace!> {

class glint_bundle_groups : public std::vector<void*> {
public:
    glint_bundle_groups() : std::vector<void*>{
<!groups!>
    } {}
};

} // namespace <!namespace!>
