#pragma once

// glint_bundle_entries_<!type!>.hpp — auto-generated by glint_bundler.mjs, do not edit.

#include "glint_bundle_entry.hpp"
#include <map>
#include <string>

namespace <!namespace!> {

class glint_bundle_library_<!type!> : public std::map<std::string, glint_bundle_entry_info*> {
public:
    glint_bundle_library_<!type!>(glint_bundle_groups& groups)
        : std::map<std::string, glint_bundle_entry_info*>{
<!entries!>
    } {}
};

} // namespace <!namespace!>
